orpheus/urls.py
from django.conf.urls import include, url
from policies.admin import admin_site
from django.views.generic import RedirectView
from rest_framework.documentation import include_docs_urls

from orpheus import views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/policies/', permanent=True)),
    url(r'^policies/', include('policies.urls', namespace='policies')),
    url(r'^admin/', admin_site.urls),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

# RESTful API
urlpatterns += [
    url(r'^api/', views.api_root),
    url(r'^api_docs/', include_docs_urls(title='Orpheus API', description='RESTful API for Orpheus')),
]

# Django-select2
urlpatterns += [
    url(r'^select2/', include('django_select2.urls')),
]

policies/urls.py
from django.conf.urls import url

from . import views

app_name = 'policies'

# Homepage and other mostly static content
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
]

# API views
urlpatterns += [
    url(r'^api/nodes/$', views.NodeSimpleListAPIView.as_view(), name='api_nodes'),
    url(r'^api/nodes/attributes/$', views.NodeListAPIView.as_view(), name='api_nodes_attributes'),
    url(r'^api/nodes/summary/$', views.NodePreferredNameListAPIView.as_view(), name='api_nodes_preferred_name'),
    url(r'^api/nodes/(?P<pk>[0-9]+)/$', views.NodeDetailAPIView.as_view(), name='api_node_detail'),
    url(r'^api/goldpolicies/$', views.GoldPolicyListAPIView.as_view(), name='api_gold'),
    url(r'^api/goldpolicies/(?P<pk>[0-9]+)/$', views.GoldPolicyDetailAPIView.as_view(), name='api_gold_detail'),
    url(r'^api/greenpolicies/$', views.GreenPolicyListAPIView.as_view(), name='api_green'),
    url(r'^api/greenpolicies/(?P<pk>[0-9]+)/$', views.GreenPolicyDetailAPIView.as_view(), name='api_green_detail'),
    url(r'^api/oastatus/$', views.OaStatusListAPIView.as_view(), name='api_oa_status'),
    url(r'^api/oastatus/(?P<pk>[0-9]+)/$', views.OaStatusDetailAPIView.as_view(), name='api_oa_status_detail'),
    url(r'^api/deals/$', views.DealListAPIView.as_view(), name='api_deal'),
    url(r'^api/deals/(?P<pk>[0-9]+)/$', views.DealDetailAPIView.as_view(), name='api_deal_detail'),
    url(r'^api/epmc/$', views.EpmcListAPIView.as_view(), name='api_epmc'),
    url(r'^api/epmc/(?P<pk>[0-9]+)/$', views.EpmcDetailAPIView.as_view(), name='api_epmc_detail'),
    url(r'^api/sources/$', views.SourceListAPIView.as_view(), name='api_source'),
    url(r'^api/sources/(?P<pk>[0-9]+)/$', views.SourceDetailAPIView.as_view(), name='api_source_detail'),
    url(r'^api/licences/$', views.LicenceListAPIView.as_view(), name='api_licence'),
    url(r'^api/outlets/$', views.OutletListAPIView.as_view(), name='api_outlet'),
    url(r'^api/versions/$', views.VersionListAPIView.as_view(), name='api_version'),
]

# Personalized API views
urlpatterns += [
    url(r'^api/cambridge/$', views.CambridgeListAPIView.as_view(), name='api_cambridge'),
]

# Autocomplete views
urlpatterns += [
    url(r'^nodeautocomplete/$', views.NodeAutocomplete.as_view(), name='node_autocomplete'),
    url(r'^publisherautocomplete/$', views.PublisherAutocomplete.as_view(),
        name='publisher_autocomplete'),
    url(r'^sourceautocomplete/$', views.SourceAutocomplete.as_view(), name='source_autocomplete'),
]

# List views
urlpatterns += [
    url(r'^journals/$', views.JournalListView.as_view(), name='journals'),
    url(r'^publishers/$', views.PublisherListView.as_view(), name='publishers'),
    url(r'^conferences/$', views.ConferenceListView.as_view(), name='conferences'),
    url(r'^sources/$', views.SourceListView.as_view(), name='sources'),
    url(r'^(?P<pk>[0-9]+)/journals/$', views.JournalbyPublisherListView.as_view(), name='journals_by_publisher'),
]

# Curatorial list views
urlpatterns += [
    url(r'^grandchildren/$', views.GrandchildrenListView.as_view(), name='grandchildren'),
    url(r'^journalchildren/$', views.JournalchildrenListView.as_view(), name='journalchildren'),
    url(r'^problematicpolicies/$', views.ProblematicPolicies.as_view(), name='problematic_policies'),
    url(r'^synonymchildren/$', views.SynonymchildrenListView.as_view(), name='synonymchildren'),
    url(r'^synonymofsynonym/$', views.SynonymofsynonymListView.as_view(), name='synonymofsynonym'),
    url(r'^synonymswithpolicies/$', views.SynonymswithpoliciesListView.as_view(), name='synonymswithpolicies'),
]

# Detail views
urlpatterns += [
    url(r'^(?P<pk>[0-9]+)/$', views.detail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/all/$', views.NodeAllDetail.as_view(), name='node_all_detail'),
    url(r'^source/(?P<pk>[0-9]+)/$', views.SourceDetail.as_view(), name='source_detail'),
]

# Node forms
urlpatterns += [
    url(r'^newnode/$', views.NodeCreate.as_view(), name='node_add'),
    url(r'^newjournal/$', views.JournalCreate.as_view(), name='journal_add'),
    url(r'^newpublisher/$', views.PublisherCreate.as_view(), name='publisher_add'),
    url(r'^newconference/$', views.ConferenceCreate.as_view(), name='conference_add'),
    url(r'^(?P<pk>[0-9]+)/newchild/$', views.ChildCreate.as_view(), name='child_add'),
    url(r'^(?P<pk>[0-9]+)/newsynonym/$', views.SynonymCreate.as_view(), name='synonym_add'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.NodeUpdate.as_view(), name='updateNode'),
    url(r'^(?P<pk>[0-9]+)/editpublisher/$', views.PublisherUpdate.as_view(), name='publisher_update'),
    url(r'^(?P<pk>[0-9]+)/editjournal/$', views.JournalUpdate.as_view(), name='journal_update'),
    url(r'^(?P<pk>[0-9]+)/editconference/$', views.ConferenceUpdate.as_view(), name='conference_update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.NodeDelete.as_view(), name='node_delete'),
    url(r'^(?P<pk>[0-9]+)/confirmdelete/$', views.NodeConfirmDelete.as_view(), name='node_confirm_delete'),
]

# OA status forms
urlpatterns += [
    url(r'^(?P<pk>[0-9]+)/newoastatus/$', views.OaStatusCreate.as_view(), name='oa_status_add'),
    url(r'^oastatus/(?P<pk>[0-9]+)/edit/$', views.OaStatusUpdate.as_view(), name='oa_status_update'),
    url(r'^oastatus/(?P<pk>[0-9]+)/delete/$', views.OaStatusDelete.as_view(), name='oa_status_delete'),
    url(r'^oastatus/(?P<pk>[0-9]+)/confirmdelete/$', views.OaStatusConfirmDelete.as_view(), name='oa_status_confirm_delete'),
]

# Gold policy forms
urlpatterns += [
    url(r'^(?P<pk>[0-9]+)/newgoldpolicy/$', views.GoldPolicyCreate.as_view(), name='gold_policy_add'),
    url(r'^goldpolicies/(?P<pk>[0-9]+)/edit/$', views.GoldPolicyUpdate.as_view(), name='gold_policy_update'),
    url(r'^goldpolicies/(?P<pk>[0-9]+)/delete/$', views.GoldPolicyDelete.as_view(), name='gold_policy_delete'),
    url(r'^goldpolicies/(?P<pk>[0-9]+)/confirmdelete/$', views.GoldPolicyConfirmDelete.as_view(), name='gold_policy_confirm_delete'),
]

# Green policy forms
urlpatterns += [
    url(r'^(?P<pk>[0-9]+)/newgreenpolicy/$', views.GreenPolicyCreate.as_view(), name='green_policy_add'),
    url(r'^greenpolicies/(?P<pk>[0-9]+)/edit/$', views.GreenPolicyUpdate.as_view(), name='green_policy_update'),
    url(r'^greenpolicies/(?P<pk>[0-9]+)/delete/$', views.GreenPolicyDelete.as_view(), name='green_policy_delete'),
    url(r'^greenpolicies/(?P<pk>[0-9]+)/confirmdelete/$', views.GreenPolicyConfirmDelete.as_view(), name='green_policy_confirm_delete'),
]

# Epmc forms
urlpatterns += [
    url(r'^(?P<pk>[0-9]+)/newepmc/$', views.EpmcCreate.as_view(), name='epmc_add'),
    url(r'^epmc/(?P<pk>[0-9]+)/edit/$', views.EpmcUpdate.as_view(), name='epmc_update'),
    url(r'^epmc/(?P<pk>[0-9]+)/delete/$', views.EpmcDelete.as_view(), name='epmc_delete'),
    url(r'^epmc/(?P<pk>[0-9]+)/confirmdelete/$', views.EpmcConfirmDelete.as_view(), name='epmc_confirm_delete'),
]

# Deal forms
urlpatterns += [
    url(r'^(?P<pk>[0-9]+)/newdeal/$', views.DealCreate.as_view(), name='deal_add'),
    url(r'^deal/(?P<pk>[0-9]+)/edit/$', views.DealUpdate.as_view(), name='deal_update'),
    url(r'^deal/(?P<pk>[0-9]+)/delete/$', views.DealDelete.as_view(), name='deal_delete'),
    url(r'^deal/(?P<pk>[0-9]+)/confirmdelete/$', views.DealConfirmDelete.as_view(), name='deal_confirm_delete'),
]

# Contact forms
urlpatterns += [
    url(r'^(?P<pk>[0-9]+)/newcontact/$', views.ContactCreate.as_view(), name='contact_add'),
    url(r'^contact/(?P<pk>[0-9]+)/edit/$', views.ContactUpdate.as_view(), name='contact_update'),
    url(r'^contact/(?P<pk>[0-9]+)/delete/$', views.ContactDelete.as_view(), name='contact_delete'),
    url(r'^contact/(?P<pk>[0-9]+)/confirmdelete/$', views.ContactConfirmDelete.as_view(), name='contact_confirm_delete'),
]

# Source forms
urlpatterns += [
    url(r'^source/add/$', views.SourceCreate.as_view(), name='source_add'),
    url(r'^source/(?P<pk>[0-9]+)/edit/$', views.SourceUpdate.as_view(), name='source_update'),
    url(r'^source/(?P<pk>[0-9]+)/delete/$', views.SourceDelete.as_view(), name='source_delete'),
    url(r'^source/(?P<pk>[0-9]+)/confirmdelete/$', views.SourceConfirmDelete.as_view(), name='source_confirm_delete'),
]

# Note forms
urlpatterns += [
    url(r'^source/(?P<pk>[0-9]+)/addnote/$', views.SourceAddNote.as_view(), name='source_add_note'),
    # url(r'^contact/(?P<pk>[0-9]+)/addnote/$', views.ContactAddNote.as_view(), name='contact_add_note'),
    # url(r'^deal/(?P<pk>[0-9]+)/addnote/$', views.DealAddNote.as_view(), name='deal_add_note'),
    # url(r'^epmc/(?P<pk>[0-9]+)/addnote/$', views.EpmcAddNote.as_view(), name='epmc_add_note'),
    url(r'^greenpolicies/(?P<pk>[0-9]+)/addnote/$', views.GreenPolicyAddNote.as_view(), name='green_policy_add_note'),
    url(r'^goldpolicies/(?P<pk>[0-9]+)/addnote/$', views.GoldPolicyAddNote.as_view(), name='gold_policy_add_note'),
    url(r'^oastatus/(?P<pk>[0-9]+)/addnote/$', views.OaStatusAddNote.as_view(), name='oa_status_add_note'),
    # url(r'^(?P<pk>[0-9]+)/addnote/$', views.NodeAddNote.as_view(), name='node_add_note'),
]

# Licence.json forms
urlpatterns += [
    url(r'^licence/add/$', views.LicenceCreate.as_view(), name='licence_add'),
]

policies/forms.py
from django import forms
from django.core.urlresolvers import reverse_lazy
from django_addanother.widgets import AddAnotherWidgetWrapper, AddAnotherEditSelectedWidgetWrapper
from dal import autocomplete
from . import models

# region Node forms
class NodeForm(forms.ModelForm):
    vetted = forms.BooleanField(disabled=True)
    vetted_date = forms.DateTimeField(disabled=True)

    class Meta:
        model = models.Node
        fields = '__all__'
        widgets = {
            'synonym_of': AddAnotherWidgetWrapper(
                autocomplete.ModelSelect2(url='policies:node_autocomplete', forward=['type']),
                reverse_lazy('policies:node_add'),
            ),
            'parent': AddAnotherWidgetWrapper(
                autocomplete.ModelSelect2(url='policies:publisher_autocomplete'),
                reverse_lazy('policies:node_add'),
            ),
            'source': AddAnotherWidgetWrapper(
                autocomplete.ModelSelect2(url='policies:source_autocomplete'),
                # forms.Select,
                reverse_lazy('policies:source_add'),
            ),
        }

class ChildNodeForm(NodeForm):
    '''
    Subclass of NodeForm for adding children nodes
    '''

    class Meta(NodeForm.Meta): # https://docs.djangoproject.com/en/1.11/topics/db/models/#meta-inheritance
        exclude = ['parent']

class PublisherNodeForm(NodeForm):
    '''
    Subclass of NodeForm for adding publisher nodes
    '''
    name = forms.CharField(label='Publisher name')

    class Meta(NodeForm.Meta):
        exclude = ['issn', 'eissn', 'type', 'parent', 'epmc_url']

class JournalNodeForm(NodeForm):
    '''
    Subclass of NodeForm for adding journal nodes
    '''
    name = forms.CharField(label='Journal name')

    class Meta(NodeForm.Meta):
        exclude = ['type', 'romeo_id']

class ConferenceNodeForm(NodeForm):
    '''
    Subclass of NodeForm for adding conference nodes
    '''
    name = forms.CharField(label='Conference name')

    class Meta(NodeForm.Meta):
        exclude = ['type', 'romeo_id']

# endregion

class DeleteForm(forms.ModelForm):
    class Meta:
        model = models.Note
        fields = ['text']
        labels = {'text': 'Reason', }

class SourceForm(forms.ModelForm):
    class Meta:
        model = models.Source
        fields = '__all__'

class LicenceForm(forms.ModelForm):
    class Meta:
        model = models.Licence
        fields = '__all__'

class ListViewSearchForm(forms.Form):
    search_text = forms.CharField(label='Phrase match',
                                  required=False,
                                  widget=forms.TextInput(attrs={'placeholder': 'name or issn'})
                                  )
    search_name_exact = forms.CharField(label='Exact match',
                                  required=False,
                                  widget=forms.TextInput(attrs={'placeholder': 'name or issn'})
                                  )

class ListViewSearchFormSources(forms.Form):
    search_text = forms.CharField(label='Phrase match',
                                  required=False,
                                  widget=forms.TextInput(attrs={'placeholder': 'name or url'})
                                  )
    search_name_exact = forms.CharField(label='Exact match',
                                  required=False,
                                  widget=forms.TextInput(attrs={'placeholder': 'name or url'})
                                  )

# region policies
class NodeAttributeForm(forms.ModelForm):
    vetted = forms.BooleanField(disabled=True)
    vetted_date = forms.DateTimeField(disabled=True)

    class Meta:
        exclude = ['node']
        widgets = {
            'source': AddAnotherWidgetWrapper(
                autocomplete.ModelSelect2(url='policies:source_autocomplete'),
                # forms.Select,
                reverse_lazy('policies:source_add'),
            ),
            'vetted_date': forms.DateInput(
                attrs={'type': 'date'}  # https://stackoverflow.com/a/41942774
            ),
            'last_checked': forms.DateInput(
                attrs={'type': 'date'}  # https://stackoverflow.com/a/41942774
            ),
            'superseded_date': forms.DateInput(
                attrs={'type': 'date'}  # https://stackoverflow.com/a/41942774
            ),
            'default_licence': AddAnotherWidgetWrapper( # Gold policy field
                forms.Select,
                reverse_lazy('policies:licence_add'),
            ),
            'version_green_licence': AddAnotherWidgetWrapper( # Green policy field
                forms.Select,
                reverse_lazy('policies:licence_add'),
            ),
            'outlet': forms.SelectMultiple(
                attrs={'size': 8}
            ),
            'version': forms.SelectMultiple(
                attrs={'size': 5}
            ),
        }

class OaStatusForm(NodeAttributeForm):
    class Meta(NodeAttributeForm.Meta):
        model = models.OaStatus

class GoldPolicyForm(NodeAttributeForm):
    class Meta(NodeAttributeForm.Meta):
        model = models.GoldPolicy

class GreenPolicyForm(NodeAttributeForm):
    class Meta(NodeAttributeForm.Meta):
        model = models.GreenPolicy

class EpmcForm(NodeAttributeForm):
    class Meta(NodeAttributeForm.Meta):
        model = models.Epmc

class DealForm(NodeAttributeForm):
    class Meta(NodeAttributeForm.Meta):
        model = models.Deal
# endregion

class ContactForm(forms.ModelForm):
    class Meta:
        model = models.Contact
        exclude = ['node']

# region Note forms
class NoteForm(forms.ModelForm):
    class Meta:
        model = models.Note
        fields = ['text']
        labels = {'text': 'Note', }
# endregion

policies/templates/policies/conference_list_view.html
{% extends "policies/base_list_view.html" %}

{% block nodetype %}conferences{% endblock %}
{% block nodetype1 %}Conferences{% endblock %}
{% block nodetype2 %}conferences{% endblock %}
{% block newnode %}<a href="{% url 'policies:conference_add' %}">[add new]</a>{% endblock %}

policies/templates/policies/contact_confirm_delete.html
{% extends "policies/base_confirm_delete.html" %}

{% block message %}
    <h3>Are you sure you want to delete contact</h3>
    <h1>"{{ object }}"?</h1>
{% endblock %}

policies/templates/policies/contact_delete_form.html
{% extends "policies/base_form.html" %}

{% block header %}
    <h2 style="display: inline">Request deletion of contact:</h2>
    <h1>{{ oastatus }}</h1>
{% endblock %}

policies/templates/policies/deal_update_form.html
{% extends "policies/base_form.html" %}

{% load staticfiles %}

{% block extrahead %}
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{{ form.media }}
{% endblock %}

{% block header %}
    <h2>Editing deal/discount of:</h2>
    <h1 style="display: inline">{{ object.node }} ({{ object.node.get_type_display }})</h1>
{% endblock %}

policies/templates/policies/empc_confirm_delete.html
{% extends "policies/base_confirm_delete.html" %}

{% block message %}
    <h3>Are you sure you want to delete EPMC policy</h3>
    <h1>"{{ object }}"?</h1>
{% endblock %}

policies/templates/policies/epmc_delete_form.html
{% extends "policies/base_form.html" %}

{% block header %}
    <h2 style="display: inline">Request deletion of EPMC policy:</h2>
    <h1>{{ oastatus }}</h1>
{% endblock %}

policies/templates/policies/epmc_update_form.html
{% extends "policies/base_form.html" %}

{% load staticfiles %}

{% block extrahead %}
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{{ form.media }}
{% endblock %}

{% block header %}
    <h2>Editing EPMC policy of:</h2>
    <h1 style="display: inline">{{ object.node }} ({{ object.node.get_type_display }})</h1>
{% endblock %}

policies/templates/policies/node_create_form.html
{% extends "policies/base_form.html" %}

{% load staticfiles %}

{% block header %}
    <h1 style="display: inline">Create new node</h1>
{% endblock %}

policies/templates/policies/node_synonym_create_form.html
{% extends "policies/base_form.html" %}

{% block header %}
    <h2 style="display: inline">Create new synonym of:</h2>
    <h1>{{ preferred_name.name }} ({{ preferred_name.get_type_display }})</h1>
{% endblock %}

policies/templates/policies/note_create_form.html
{% extends "policies/base_form.html" %}

{% block header %}
    <h2 style="display: inline">Create new note for:</h2>
    <h1>{{ note_parent }}</h1>
{% endblock %}

policies/templates/policies/oastatus_delete_form.html
{% extends "policies/base_form.html" %}

{% block header %}
    <h2 style="display: inline">Request deletion of OA status:</h2>
    <h1>{{ oastatus }}</h1>
{% endblock %}

policies/templates/policies/oastatus_update_form.html
{% extends "policies/base_form.html" %}

{% load staticfiles %}

{% block extrahead %}
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{{ form.media }}
{% endblock %}

{% block header %}
    <h2>Editing OA status of:</h2>
    <h1 style="display: inline">{{ object.node }} ({{ object.node.get_type_display }})</h1>
{% endblock %}

policies/templates/policies/related_widget_wrapper.html
{% load i18n static %}
<div class="related-widget-wrapper">
    {{ rendered_widget }}
    {% block links %}
        {% spaceless %}
        {% if can_change_related %}
        <a class="related-widget-wrapper-link change-related" id="change_id_{{ name }}"
            data-href-template="{{ change_related_template_url }}?{{ url_params }}"
            title="{% blocktrans %}Change selected {{ model }}{% endblocktrans %}">
            <img src="{% static 'admin/img/icon-changelink.svg' %}" alt="{% trans 'Change' %}"/>
        </a>
        {% endif %}
        {% if can_add_related %}
        <a class="related-widget-wrapper-link add-related" id="add_id_{{ name }}"
            href="{{ add_related_url }}?{{ url_params }}"
            title="{% blocktrans %}Add another {{ model }}{% endblocktrans %}">
            <img src="{% static 'images/icon-addlink.svg' %}" alt="{% trans 'Add' %}"/>
        </a>
        {% endif %}
        {% if can_delete_related %}
        <a class="related-widget-wrapper-link delete-related" id="delete_id_{{ name }}"
            data-href-template="{{ delete_related_template_url }}?{{ url_params }}"
            title="{% blocktrans %}Delete selected {{ model }}{% endblocktrans %}">
            <img src="{% static 'admin/img/icon-deletelink.svg' %}" alt="{% trans 'Delete' %}"/>
        </a>
        {% endif %}
        {% endspaceless %}
    {% endblock %}
</div>